{
  "hash": "23a491d3377fef516b9a43da858bb2f2",
  "result": {
    "markdown": "---\ntitle: \"Credit Card Fraud: A Tidymodels Tutorial\"\ndescription: \"An Imbalanced Class Problem\"\ntwitter-card:\n  image: \"thumbnail.png\"\nauthor:\n  - name: Louise E. Sinks\n    url: https://lsinks.github.io/\ndate: 04-11-2023\ncategories: [R, R-code, tidymodels, Machine Learning, classifiers] # self-defined categories\ncitation:\n  url: https://lsinks.github.io/posts/2023-04-11-credit-card-fraud/fraud_tutorial\nimage: \"thumbnail.png\"\ndraft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!\n---\n\n\n# 1. Classification using tidymodels\n\nI will walk through a classification problem from importing the data, cleaning, exploring, fitting, choosing a model, and finalizing the model.\n\nI wanted to create a project that could serve as a template for other two-class classification problems. I also wanted to fully use the tidymodels framework, particularly more advanced functionalities like workflowsets. There are some great tutorials on tidymodels, in particular [Olivier Gimenez's tutorial on Kaggle's Titanic competition](https://oliviergimenez.github.io/learning-machine-learning/). This tutorial steps through each model individually, while I wanted to use the more streamlined approach offered by workflowsets. I also found myself confused as I started doing more advanced procedures in tidymodels, despite having read the book [Tidy Modeling with R](https://www.tmwr.org/) multiple times and working through several tutorials on [Julia Silge's excellent blog](https://juliasilge.com/). I ended up writing my own [tutorial on tidymodels objects](https://lsinks.github.io/posts/2023-04-10-tidymodels/tidymodels_tutorial) that goes through the differences in the various ways to perform fitting and the various objects produced.\n\nIn addition to providing a template for the machine learning portion, I wanted to create nice figures and tables that could also be re-used.\n\nI will also have a different version of this code on Datacamp. I've numbered the code chunks manually to aid in comparison between the two versions. I start numbering at 2, because Code Block 1 will be installing libraries at the Datacamp workspace. There are some important differences between the RStudio environment and online notebooks/workspaces.\n\nPlease feel free to copy and use any of my code in your work. I'd appreciate an acknowledgment or link back if you find this tutorial useful.\n\n# 2. The problem: predicting credit card fraud\n\nThe goal of the project is to correctly predict fraudulent credit card transactions.\n\nThe specific problem is one provided by Datacamp as a challenge in the certification community. The dataset (Credit Card Fraud) can also be found at the Datacamp workspace. To access the dataset and the data dictionary, you can create a new notebook on datacamp using the Credit Card Fraud dataset. That will produce a notebook like [this](https://app.datacamp.com/workspace/w/f3a94059-683b-4bc6-b354-9b98cf3d5242/edit) with the dataset and the data dictionary.\n\nThe original source of the data (prior to preparation by DataCamp) can be found [here](https://www.kaggle.com/kartik2112/fraud-detection?select=fraudTrain.csv).\n\n# 3. Set-up steps\n\nLoading the necessary libraries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 2: Loading Libraries\n\n# loading tidyverse/ tidymodels packages\nlibrary(tidyverse) #core tidyverse\nlibrary(tidymodels) # tidymodels framework\nlibrary(lubridate) # date/time handling\n\n# visualization\nlibrary(viridis) #color scheme that is colorblind friendly\nlibrary(ggthemes) # themes for ggplot\nlibrary(gt) # to make nice tables\nlibrary(cowplot) # to make multi-panel figures\nlibrary(corrplot) # nice correlation plot\n\n#Data Cleaning\nlibrary(skimr) #provides overview of data and missingness\n\n#Geospatial Data\nlibrary(tidygeocoder) #converts city/state to lat/long\n\n#Modeling\nlibrary(ranger) # random forest\nlibrary(glmnet) # elastic net logistic regression\nlibrary(themis) # provides up/down-sampling methods for the data\nlibrary(lightgbm) # fast gradient-boosted machine algo\nlibrary(bonsai) #provides parnsip objects for tree-based models\n```\n:::\n\n\nI'm setting a global theme for my figures. I'm using [cowplot](https://wilkelab.org/cowplot/index.html) to create some composite figures, and apparently you must choose a cowplot theme if you set a global theme. You can use a ggtheme on a graph by graph basis, but not globally.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 3: setting global figure options\n\ntheme_set(theme_cowplot(12))\n```\n:::\n\n\nLoading the data. This is a local copy that is part of the workspace download from Datacamp.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 4: Reading in the data\nfraud <- read_csv('datacamp_workspace/credit_card_fraud.csv', show_col_types = FALSE) \nfraud\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 339,607 × 15\n   trans_date_trans_time merchant        category    amt city  state   lat  long\n   <dttm>                <chr>           <chr>     <dbl> <chr> <chr> <dbl> <dbl>\n 1 2019-01-01 00:00:44   Heller, Gutman… grocery… 107.   Orie… WA     48.9 -118.\n 2 2019-01-01 00:00:51   Lind-Buckridge  enterta… 220.   Mala… ID     42.2 -112.\n 3 2019-01-01 00:07:27   Kiehn Inc       grocery…  96.3  Gren… CA     41.6 -123.\n 4 2019-01-01 00:09:03   Beier-Hyatt     shoppin…   7.77 High… NM     32.9 -106.\n 5 2019-01-01 00:21:32   Bruen-Yost      misc_pos   6.85 Free… WY     43.0 -111.\n 6 2019-01-01 00:22:06   Kunze Inc       grocery…  90.2  Hono… HI     20.1 -155.\n 7 2019-01-01 00:22:18   Nitzsche, Kess… shoppin…   4.02 Vale… NE     42.8 -101.\n 8 2019-01-01 00:22:36   Kihn, Abernath… shoppin…   3.66 West… OR     43.8 -122.\n 9 2019-01-01 00:31:51   Ledner-Pfanner… gas_tra… 102.   Thom… UT     39.0 -110.\n10 2019-01-01 00:34:10   Stracke-Lemke   grocery…  83.1  Conw… WA     48.3 -122.\n# ℹ 339,597 more rows\n# ℹ 7 more variables: city_pop <dbl>, job <chr>, dob <date>, trans_num <chr>,\n#   merch_lat <dbl>, merch_long <dbl>, is_fraud <dbl>\n```\n:::\n:::\n\n\n# 4. Validation of data types\n\nI examine the dataset via `skim` and make sure all data elements are as expected. `skim` is a function in the [skimr package](https://cran.r-project.org/web/packages/skimr/index.html) that provides a high-level summary of the data. The output is a dataframe, [so it can be manipulated and formatted more nicely](https://lsinks.github.io/posts/2023-03-24-tidytuesday-figure-polishing/#skimr-to-understand-your-data) than the output of `summary()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 5: Validation of Data Types Against Data Dictionary\n# custom skim function to remore some of the quartile data\nmy_skim <- skim_with(numeric = sfl(p25 = NULL, p50 = NULL, p75 = NULL))\n\nmy_skim(fraud)\n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |       |\n|:------------------------|:------|\n|Name                     |fraud  |\n|Number of rows           |339607 |\n|Number of columns        |15     |\n|_______________________  |       |\n|Column type frequency:   |       |\n|character                |6      |\n|Date                     |1      |\n|numeric                  |7      |\n|POSIXct                  |1      |\n|________________________ |       |\n|Group variables          |None   |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|merchant      |         0|             1|   7|  37|     0|      693|          0|\n|category      |         0|             1|   4|  14|     0|       14|          0|\n|city          |         0|             1|   4|  25|     0|      176|          0|\n|state         |         0|             1|   2|   2|     0|       13|          0|\n|job           |         0|             1|   6|  49|     0|      163|          0|\n|trans_num     |         0|             1|  32|  32|     0|   339607|          0|\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|dob           |         0|             1|1927-09-09 |2001-07-26 |1974-03-10 |      187|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|      mean|        sd|      p0|       p100|hist  |\n|:-------------|---------:|-------------:|---------:|---------:|-------:|----------:|:-----|\n|amt           |         0|             1|     70.58|    161.68|    1.00|   28948.90|▇▁▁▁▁ |\n|lat           |         0|             1|     39.72|      5.09|   20.03|      66.69|▁▆▇▁▁ |\n|long          |         0|             1|   -110.62|     12.65| -165.67|     -89.63|▁▁▅▇▆ |\n|city_pop      |         0|             1| 107140.87| 293029.89|   46.00| 2383912.00|▇▁▁▁▁ |\n|merch_lat     |         0|             1|     39.72|      5.13|   19.03|      67.51|▁▅▇▁▁ |\n|merch_long    |         0|             1|   -110.62|     12.66| -166.67|     -88.63|▁▁▃▇▅ |\n|is_fraud      |         0|             1|      0.01|      0.07|    0.00|       1.00|▇▁▁▁▁ |\n\n\n**Variable type: POSIXct**\n\n|skim_variable         | n_missing| complete_rate|min                 |max                 |median              | n_unique|\n|:---------------------|---------:|-------------:|:-------------------|:-------------------|:-------------------|--------:|\n|trans_date_trans_time |         0|             1|2019-01-01 00:00:44 |2020-12-31 23:59:24 |2019-12-31 15:11:23 |   338504|\n:::\n:::\n\n\nEverything looks okay, and I am lucky because there is no missing data. I will not need to do cleaning or imputation.\n\nI see that `is_fraud` is coded as 0 or 1, and the mean of this variable is 0.00525. The number of fraudulent transactions is very low, and we should use treatments for imbalanced classes when we get to the fitting/ modeling stage.\n\n# 5. Do all variables have sensible types?\n\nI will look at each variable and decide whether to keep, transform, or drop it. This is a mixture of Exploratory Data Analysis and Feature Engineering, but I find it helpful to do some simple feature engineering as I start exploring the data. In this project, we have all data to begin with, so any transformations will be performed on the entire dataset. If we had a separate test dataset, we'd need to do the transformation on that in parallel or, more ideally, do the transformations as a `recipe_step()` in the tidymodels framework. Then the transformations would be applied to any data the recipe was used on as part of the modeling workflow. There is less chance of data leakage or missing a step when you perform the feature engineering in the recipe.\n\nQuestions to consider:\n\n-   Should strings be converted to factors?\n-   Is date-time data properly encoded?\n-   Is financial data encoded numerically?\n-   Is geographic data consistently rendered? (city/ state strings vs. lat/long numeric pairs)\n\nFirst, I grouped all my variables by type and examined each variable class by class. The dataset has the following types of variables:\n\n1.  Strings\n2.  Geospatial Data\n3.  Dates\n4.  Date/Times\n5.  Numerical\n\nAs I go through the different classes of variables, I will provide information from the data dictionary about them.\n\n## 5.1. Looking at the strings\n\nStrings are usually not a useful format for classification problems. The strings should be converted to factors, dropped, or otherwise transformed.\n\n***5.1.1. Strings to Factors*** (Code Block 6 - 8)\n\n-   `category`, Category of Merchant\n-   `job`, Job of Credit Card Holder\n\n***5.1.2. Strings as Strings*** (Code Block 9)\n\n-   `merchant`, Merchant Name\n-   `trans_num`, Transaction Number\n\nI'm not going to retain these, as they are either unlikely to have predictive power (`trans_num`) or are highly correlated with other predictors (`merchant` with `merch_lat`/`merch_long`.)\n\n***5.2. Strings to Geospatial Data*** (Code Block 13)\n\nWe have plenty of geospatial data as lat/long pairs, so I want to convert city/state to lat/long so I can compare to the other geospatial variables. This will also make it easier to compute new variables like the distance the transaction is from the home location. I will transform and explore this when I handle the other geospatial data.\n\n-   `city`, City of Credit Card Holder\n-   `state`, State of Credit Card Holder\n\n**Things to consider as we walk through the data:**\n\n-   Do we have typos that lead to duplicate entries : VA/ Va. / Virginia?\n-   Do we have excessive \\# of categories? Do we want to combine some?\n-   Should they be ordered?\n\n### 5.1.1. Exploring the factors: how is the compactness of categories?\n\nThe predictors `category` and `job` are transformed into factors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 6: Converting Strings to Factors\nfraud$category <- factor(fraud$category)\nfraud$job <- factor(fraud$job)\n```\n:::\n\n\nFrom the skim output, I see that `category` has 14 unique values, and `job` has 163 unique values. The dataset is quite large, with 339,607 records, so these variables don't have an excessive number of levels at first glance. However, it is worth seeing if I can compact the levels to a smaller number.\n\n#### Why do we care about the number of categories and whether they are \"excessive\"?\n\nConsider the extreme case where a dataset had categories that only contained one record each. There is simply insufficient data to make correct predictions using category as a predictor on new data with that category label. Additionally, if your modeling uses dummy variables, having an extremely large number of categories will lead to the production of a huge number of predictors, which can slow down the fitting. This is fine if all the predictors are useful, but if they aren't useful (as in the case of having only one record for a category), trimming them will improve the speed and quality of the data fitting.\n\nIf I had subject matter expertise, I could manually combine categories. For example, in this dataset, the three largest categories in `job` are surveying-related and perhaps could be combined. If you don't have subject matter expertise, or if performing this task would be too labor intensive, then you can use cutoffs based on the amount of data in a category. If the majority of the data exists in only a few categories, then it might be reasonable to keep those categories and lump everything else in an \"other\" category or perhaps even drop the data points in smaller categories. As a side note, the [forcats package](https://forcats.tidyverse.org/) has a variety of tools to handle consolidating and dropping levels based on different cutoffs if this is the approach you decide to take.\n\nOne way to evaluate the compactness of a factor is to group the data by category and look at a table of counts. I like the [gt package](https://gt.rstudio.com/) for making attractive tables in R. (Uncomment the line in Code Block 7 `#gt:::as.tags.gt_tbl(table_3a)` to see the table.) The tabular data also shows that there aren't typos leading to duplicate categories.\n\nAnother way to evaluate the compactness is to [make a cumulative plot](https://stackoverflow.com/questions/15844919/cumulative-plot-%20using-ggplot2). This looks at the proportion of data that is described as you add categories. I'm using the [cowplot package](https://wilkelab.org/cowplot/index.html) to make multipanel figures. I want to look at both factors at once; this is fine for exploratory data analysis, but I wouldn't recommend it for a report or presentation, since there is no connection between the two variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 7: Exploring the Compactness of the Categories\n\n# Exploring the jobs factor\n# bin and count the data and return sorted\ntable_3a_data <- fraud %>% count(job, sort = TRUE) \n\n# creating a table to go with this, but not displaying it\ntable_3a <- table_3a_data %>%\n  gt() %>%\n  tab_header(title = \"Jobs of Card Holders\") %>%\n  cols_label(job = \"Jobs\", n = \"Count\") %>%\n  opt_stylize(style = 1,\n              color = \"green\",\n              add_row_striping = TRUE)\n#gt:::as.tags.gt_tbl(table_3a)  #displays the table \n\nfig_1a <- ggplot(table_3a_data, aes(\n  x = 1:nlevels(fraud$job),\n  y = (cumsum(n) * 100 / nrow(fraud))\n)) +\n  geom_point(color = \"darkcyan\") +\n  geom_hline(yintercept = 80) +  #marker for 80% of the data\n  xlab(\"jobs index\") +\n  ylab(\"% of Total\") +\n  ylim(0, 100) # +\n  #ggtitle(\"Jobs of Card Holder\")  #use if standalone graph\n\t\t\t           \n\n# same as above, but just for the category variable\ntable_3b_data <- fraud %>% count(category, sort = TRUE)\ntable_3b <- table_3b_data %>%\n  gt() %>%\n  tab_header(title = \"Transaction Category in Credit Card Fraud\") %>%\n  cols_label(category = \"Category\", n = \"Count\") %>%\n  opt_stylize(style = 1,\n              color = \"blue\",\n              add_row_striping = TRUE) #%>%\n#gt:::as.tags.gt_tbl(table_3b)\n\nfig_1b <- ggplot(table_3b_data, aes(\n  x = 1:nlevels(fraud$category),\n  y = (cumsum(n) * 100 / nrow(fraud))\n)) +\n  geom_point(color = \"darkcyan\") +\n  geom_hline(yintercept = 80) +\n  xlab(\"category index\") +\n  ylab(\"% of Total\") +\n  ylim(0, 100) #+\n#ggtitle(\"Jobs of Card Holder\") #use if standalone graph\n\n\n#this makes the panel grid and labels it\nplot_fig_1 <-\n  plot_grid(fig_1a,\n            fig_1b,\n            labels = c('A', 'B'),\n            label_size = 14)\n\n#This creates the figure title\ntitle_1 <- ggdraw() +\n  draw_label(\n    \"Figure 1: Exploring Categorical Variables\",\n    fontface = 'bold',\n    x = 0,\n    hjust = 0,\n    size = 14\n  ) +\n  theme(# add margin on the left of the drawing canvas,\n    # so title is aligned with left edge of first plot\n    plot.margin = margin(0, 0, 0, 7))\n\n#this combines the panel grid, title, and displays both\nplot_grid(title_1,\n          plot_fig_1,\n          ncol = 1,\n          # rel_heights values control vertical title margins\n          rel_heights = c(0.1, 1))\n```\n\n::: {.cell-output-display}\n![](fraud_tutorial_files/figure-html/compactness-1.png){width=672}\n:::\n:::\n\n\nIf you look at Figure 1A, roughly 75-80 categories have to be included to capture 80% of the data. For Figure 1B, roughly ten categories have to be included. Ideally, you'd like a very steep curve initially (where a \"small number\" of categories cover the \"majority\" of the data) and then a long, shallow tail approaching 100% that corresponds to the data to be binned in \"other\" or dropped. There aren't hard and fast rules on making these decisions. I decided to use 80% as my threshold. Both of these curves look relatively shallow to me, so I decided not to do any binning, grouping, or dropping of levels.\n\nI decided to look at all the categories of transactions just to see which ones were the most common.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 8: Exploring the Category factor\nggplot(fraud, aes(fct_infreq(category))) +\n  geom_bar(color = \"darkcyan\", fill = \"darkcyan\") +\n  ggtitle(\"Figure 2: Types of Transactions\") +\n  coord_flip() +\n  ylab(\"Count\") +\n  xlab(\"Merchant Type\")\n```\n\n::: {.cell-output-display}\n![](fraud_tutorial_files/figure-html/category-levels-1.png){width=672}\n:::\n:::\n\n\nGas/transport was the most common category, and grocery was the second most common, both of which make sense. The least common category was travel. Nothing seemed unusual in the ranking.\n\n### 5.1.2. Looking at our character strings\n\nMerchant name (`merchant`) and transaction number(`trans_num`) are both strings. Transaction number should not influence fraud rate as it is a number assigned to the transaction when processed. I will drop it from our dataset. Merchant name could be correlated with fraud, for example, if a company's employee was involved. However, this data is also represented by the location and category. If a location/category is found to have higher levels of fraud, then a more detailed examination of those transactions can be performed, including the merchant name. Here, I also remove it from the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 9: Removing Character/ String Variables\nfraud <- fraud %>%\n  select(-merchant,-trans_num)\n```\n:::\n\n\n## 5.2. Looking at the geographic data\n\nThis data is coded as numeric (latitude and longitude) or character (city/state), but we can recognize it as geographic data and treat it appropriately.\n\nFirst, there are two sets of geographic data related to the merchant. The location of the merchant and where the transaction occurred. I create scatter plots of latitude and longitude separately, because I want to check the correlation between the two sources of data (merchant and transaction). I create a shared legend following the article [here](https://wilkelab.org/cowplot/articles/shared_legends.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 10: Comparing Merchant and Transaction Locations\n\n# calculate correlations\ncor_lat <- round(cor(fraud$lat, fraud$merch_lat), 3)\ncor_long <- round(cor(fraud$long, fraud$merch_long), 3)\n\n# make figure\nfig_3a <-\n  ggplot(fraud, aes(lat, merch_lat, fill = factor(is_fraud))) +\n  geom_point(\n    alpha = 1,\n    shape = 21,\n    colour = \"black\",\n    size = 5\n  ) +\n  ggtitle(\"Latitude\") +\n  ylab(\"Merchant Latitude\") +\n  xlab(\"Transaction Latitude\") +\n  scale_fill_viridis(\n    discrete = TRUE,\n    labels = c('Not Fraud', 'Fraud'),\n    name = \"\"\n  ) +\n  geom_abline(slope = 1, intercept = 0) \n\nfig_3b <-\n  ggplot(fraud, aes(long, merch_long, fill = factor(is_fraud))) +\n  geom_point(\n    alpha = 1,\n    shape = 21,\n    colour = \"black\",\n    size = 5\n  ) +\n  ggtitle(\"Longitude\") +\n  ylab(\"Merchant Longitude\") +\n  xlab(\"Transaction Longitude\") +\n  scale_fill_viridis(\n    discrete = TRUE,\n    labels = c('Not Fraud', 'Fraud'),\n    name = \"\"\n  ) +\n  geom_abline(slope = 1, intercept = 0) \n\n# create the plot with the two figs on a grid, no legend\nprow_fig_3 <- plot_grid(\n  fig_3a + theme(legend.position = \"none\"),\n  fig_3b + theme(legend.position = \"none\"),\n  align = 'vh',\n  labels = c(\"A\", \"B\"),\n  label_size = 12,\n  hjust = -1,\n  nrow = 1\n)\n\n# extract the legend from one of the figures\nlegend <- get_legend(\n  fig_3a + \n    guides(color = guide_legend(nrow = 1)) +\n    theme(legend.position = \"bottom\")\n)\n\n# add the legend to the row of figures, prow_fig_3\nplot_fig_3 <- plot_grid(prow_fig_3, legend, ncol = 1, rel_heights = c(1, .1))\n\n# title\ntitle_3 <- ggdraw() +\n  draw_label(\n    \"Figure 3. Are Merchant and Transaction Coordinates Correlated?\",\n    fontface = 'bold',\n    size = 14,\n    x = 0,\n    hjust = 0\n  ) +\n  theme(plot.margin = margin(0, 0, 0, 7))\n\n# graph everything\nplot_grid(title_3,\n          plot_fig_3,\n          ncol = 1,\n          rel_heights = c(0.1, 1))\n```\n\n::: {.cell-output-display}\n![](fraud_tutorial_files/figure-html/transaction-merchant-coords-1.png){width=672}\n:::\n:::\n\n\nThese two sets of data are highly correlated (for latitude = 0.994 and for longitude = 0.999) and thus are redundant. So I remove `merch_lat` and `merch_long` from the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 11: Removing merch_lat and merch_long\nfraud <- fraud %>%\n  select(-merch_lat,-merch_long) %>%\n  rename(lat_trans = lat, long_trans = long)\n```\n:::\n\n\nNext, I will look and see if some locations are more prone to fraud.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 12: Looking at Fraud by Location\nggplot(fraud, aes(long_trans, lat_trans, fill = factor(is_fraud))) +\n  geom_point(\n    alpha = 1,\n    shape = 21,\n    colour = \"black\",\n    size = 5,\n    position = \"jitter\"\n  ) +\n  scale_fill_viridis(\n    discrete = TRUE,\n    labels = c('Not Fraud', 'Fraud'),\n    name = \"\"\n  ) +\n  ggtitle(\"Figure 4: Where does fraud occur? \") +\n  ylab(\"Latitude\") +\n  xlab(\"Longitude\") \n```\n\n::: {.cell-output-display}\n![](fraud_tutorial_files/figure-html/fraud-by-location-1.png){width=672}\n:::\n:::\n\n\nIt looks like there are some locations which only have fraudulent transactions.\n\nNext, I'm going to convert city/state into latitude and longitude using the [tidygeocoder package](https://jessecambon.github.io/tidygeocoder/reference/geo.html). Also included code to save this output and then re-import it. You likely do not want to be pulling the data from the internet every time you run the code, so this gives you the option to work from a local copy. For many services, it is against terms of service to repeatedly make the same calls rather than working from a local version. I did find that I could originally pull all data from 'osm', but while double checking this code, I found that the service is now imposing some rate limit and denies some requests, leading to some NA entries. So do check your results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 13: Converting city/state data lat/long\n\n# need to pass an address to geo to convert to lat/long\nfraud <- fraud %>%\n  mutate(address = str_c(city, state, sep = \" , \"))\n\n# generate a list of distinct addresses to look up\n# the dataset is large, so it is better to only look up unique address rather that the address\n# for every record\naddress_list <- fraud %>%\n  distinct(address)\n\n# this has one more than number in the cities, so there must be a city with the same name in more than one state.\n\n#I don't want to run this api call everytime I open the notebook, so I downloaded the data and will reimport it and load it\n# Below is the code to run the call.  Uncomment it.\n# gets coordinates for city,states\n#home_coords <-\n#  geo(address_list$address,\n#      method = \"osm\",\n#      full_results = FALSE)\n#write.csv(\"home_coords_april10.csv\", home_coords)\n#home_coords <- home_coords %>%\n#  rename(lat_home = lat, long_home = long)\n\n # I downloaded it using the gui interface provided by datacamp when you view the object.\n\n\n# Reimport the data and load it\nhome_coords <-\n  read_csv('datacamp_workspace/downloaded_coords.csv', show_col_types = FALSE)\n\n\n# imported home coords has an extra set of quotation marks\nhome_coords <- home_coords %>%\n  mutate(address = str_replace_all(address, \"\\\"\", \"\")) %>%\n  rename(lat_home = lat, long_home = long)\n\n# use a left join on fraud and home_coords to assign the coord to every address in fraud\nfraud <- fraud %>%\n  left_join(home_coords, by = \"address\")\n```\n:::\n\n\nNow I'm going to calculate the distance between the card holder's home and the location of the transaction. I think distance might be a feature that is related to fraud. I followed the tutorial [here](https://www.geeksforgeeks.org/program-distance-two-points-earth/amp/) for calculating distance\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 14: Distance Between Home and Transaction\n\n# I believe this assuming a spherical Earth\n\n# convert to radians\nfraud <- fraud %>%\n  mutate(\n    lat1_radians = lat_home / 57.29577951,\n    lat2_radians = lat_trans / 57.29577951,\n    long1_radians = long_home / 57.29577951,\n    long2_radians = long_trans / 57.29577951\n  )\n\n# calculating distance\nfraud <-\n  fraud %>% mutate(distance_miles = 3963.0 * acos((sin(lat1_radians) * sin(lat2_radians)) + cos(lat1_radians) * cos(lat2_radians) * cos(long2_radians - long1_radians)\n  ))\n\n# calculating the correlation\nfraud_distance <- round(cor(fraud$distance_miles, fraud$is_fraud), 3) \n```\n:::\n\n\nDespite my assumption that distance would be correlated with fraud, the correlation value is quite low, -0.003.\n\nI'm going to visualize it anyway.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 15: Distance from Home and Fraud\nggplot(fraud, aes(distance_miles, is_fraud , fill = factor(is_fraud))) +\n  geom_point(\n    alpha = 1,\n    shape = 21,\n    colour = \"black\",\n    size = 5,\n    position = \"jitter\"\n  ) +\n  scale_fill_viridis(\n    discrete = TRUE,\n    labels = c('Not Fraud', 'Fraud'),\n    name = \"\"\n  ) +\n  ggtitle(\"Figure 5: How far from home does fraud occur?\") +\n  xlab(\"Distance from Home (miles)\") +\n  ylab(\"Is Fraud?\") \n```\n\n::: {.cell-output-display}\n![](fraud_tutorial_files/figure-html/distance-and-fraud-1.png){width=672}\n:::\n:::\n\n\nSome distances only have fraudulent transactions. This might be related to the locations that are only fraud, Figure 4.\n\nThis new feature `distances_miles` is retained, and the original variables (`city`, `state`) and the intermediate variables (address, variables used to calculate distance) are removed in Code Block 16.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 16: Remove Extraneous/Temp Variables\n\n# created to calculate distance\nfraud <- fraud %>%\n  select(-lat1_radians,-lat2_radians,-long1_radians,-long2_radians)\n\n#remove city and state and address, replaced by lat/long\nfraud <- fraud %>%\n  select(-city, -state, -address)\n```\n:::\n\n\n## 5.3. Looking at the dates\n\n**Date**\n\n`dob`, Date of Birth of Credit Card Holder\n\nQuestions:\n\n-   What is the date range, and does it make sense?\n\n-   Do we have improbably old or young people?\n\n-   Do we have historic or futuristic transaction dates?\n\nI calculate the `age` from the `dob` and visualize them both.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 17: Looking at dob\n\n#summary(fraud$dob) #if you wanted a printed summary stats\n\nfig_6a <- ggplot(fraud, aes(dob)) +\n  geom_histogram(color = \"darkcyan\",\n                 fill = \"darkcyan\" ,\n                 bins = 10) +\n  #ggtitle(\"How old are card Holders?\") +\n  ylab(\"Count\") +\n  xlab(\"Date of Birth\") \n\nfraud <- fraud %>%\n  #mutate (age = trunc((dob %--% today()) / years(1))) #if you wanted to calculate age relative to today\n  mutate(age = trunc((\n    dob %--% min(fraud$trans_date_trans_time)\n  ) / years(1)))\n#summary(fraud$age) #if you wanted a printed summary stats\n\n\nfig_6b <- ggplot(fraud, aes(age)) +\n  geom_histogram(color = \"darkcyan\",\n                 fill = \"darkcyan\",\n                 bins = 10) +\n  #ggtitle(\"How old are card holders?\") +\n  ylab(\"Count\") +\n  xlab(\"Age\") \nplot_fig_6 <- plot_grid(fig_6a, fig_6b, labels = c('A', 'B'))\n\ntitle_6 <- ggdraw() +\n  draw_label(\n    \"Figure 6. How old are the card holders?\",\n    fontface = 'bold',\n    x = 0,\n    hjust = 0\n  ) +\n  theme(# add margin on the left of the drawing canvas,\n    # so title is aligned with left edge of first plot\n    plot.margin = margin(0, 0, 0, 7))\nplot_grid(title_6,\n          plot_fig_6,\n          ncol = 1,\n          # rel_heights values control vertical title margins\n          rel_heights = c(0.1, 1))\n```\n\n::: {.cell-output-display}\n![](fraud_tutorial_files/figure-html/dob-viz-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntable_4_data <- fraud %>% count(age)\n\ntable_4 <- table_4_data %>%\n  gt() %>%\n  tab_header(title = \"Ages of Card Holders\") %>%\n  cols_label(age = \"Ages\", n = \"Count\") %>%\n  opt_stylize(style = 1,\n              color = \"green\",\n              add_row_striping = TRUE)\ngt:::as.tags.gt_tbl(table_4)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"qltvaevqnv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qltvaevqnv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qltvaevqnv thead, #qltvaevqnv tbody, #qltvaevqnv tfoot, #qltvaevqnv tr, #qltvaevqnv td, #qltvaevqnv th {\n  border-style: none;\n}\n\n#qltvaevqnv p {\n  margin: 0;\n  padding: 0;\n}\n\n#qltvaevqnv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #027101;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #027101;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qltvaevqnv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qltvaevqnv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qltvaevqnv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qltvaevqnv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qltvaevqnv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #038901;\n}\n\n#qltvaevqnv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #038901;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #038901;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qltvaevqnv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qltvaevqnv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qltvaevqnv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qltvaevqnv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qltvaevqnv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #038901;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qltvaevqnv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qltvaevqnv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #038901;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #038901;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qltvaevqnv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #038901;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #038901;\n  vertical-align: middle;\n}\n\n#qltvaevqnv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qltvaevqnv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qltvaevqnv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: none;\n  border-top-width: 1px;\n  border-top-color: #CAFFAF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #CAFFAF;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #CAFFAF;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qltvaevqnv .gt_stub {\n  color: #FFFFFF;\n  background-color: #038901;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #038901;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qltvaevqnv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qltvaevqnv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qltvaevqnv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qltvaevqnv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qltvaevqnv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #038901;\n}\n\n#qltvaevqnv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qltvaevqnv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #038901;\n}\n\n#qltvaevqnv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #CAFFAF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qltvaevqnv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #038901;\n}\n\n#qltvaevqnv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #038901;\n}\n\n#qltvaevqnv .gt_striped {\n  background-color: #F4F4F4;\n}\n\n#qltvaevqnv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #038901;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #038901;\n}\n\n#qltvaevqnv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qltvaevqnv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qltvaevqnv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qltvaevqnv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qltvaevqnv .gt_left {\n  text-align: left;\n}\n\n#qltvaevqnv .gt_center {\n  text-align: center;\n}\n\n#qltvaevqnv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qltvaevqnv .gt_font_normal {\n  font-weight: normal;\n}\n\n#qltvaevqnv .gt_font_bold {\n  font-weight: bold;\n}\n\n#qltvaevqnv .gt_font_italic {\n  font-style: italic;\n}\n\n#qltvaevqnv .gt_super {\n  font-size: 65%;\n}\n\n#qltvaevqnv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qltvaevqnv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qltvaevqnv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qltvaevqnv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qltvaevqnv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qltvaevqnv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qltvaevqnv .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Ages of Card Holders</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Ages\">Ages</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Count\">Count</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">17</td>\n<td headers=\"n\" class=\"gt_row gt_right\">2190</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">18</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">2198</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">19</td>\n<td headers=\"n\" class=\"gt_row gt_right\">6592</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">20</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">741</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">21</td>\n<td headers=\"n\" class=\"gt_row gt_right\">2207</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">22</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">31</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">23</td>\n<td headers=\"n\" class=\"gt_row gt_right\">3663</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">25</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">3659</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">26</td>\n<td headers=\"n\" class=\"gt_row gt_right\">6587</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">27</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">4378</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">28</td>\n<td headers=\"n\" class=\"gt_row gt_right\">2926</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">29</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">8772</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">30</td>\n<td headers=\"n\" class=\"gt_row gt_right\">17525</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">31</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">16093</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">32</td>\n<td headers=\"n\" class=\"gt_row gt_right\">2940</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">33</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">10220</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">34</td>\n<td headers=\"n\" class=\"gt_row gt_right\">11675</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">35</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">2204</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">36</td>\n<td headers=\"n\" class=\"gt_row gt_right\">10218</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">37</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">9489</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">38</td>\n<td headers=\"n\" class=\"gt_row gt_right\">8049</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">39</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">5120</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">40</td>\n<td headers=\"n\" class=\"gt_row gt_right\">8017</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">41</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">1467</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">42</td>\n<td headers=\"n\" class=\"gt_row gt_right\">6592</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">43</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">5847</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">44</td>\n<td headers=\"n\" class=\"gt_row gt_right\">14619</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">45</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">14608</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">46</td>\n<td headers=\"n\" class=\"gt_row gt_right\">13888</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">47</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">8015</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">48</td>\n<td headers=\"n\" class=\"gt_row gt_right\">1500</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">49</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">5135</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">50</td>\n<td headers=\"n\" class=\"gt_row gt_right\">1482</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">51</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">12449</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">52</td>\n<td headers=\"n\" class=\"gt_row gt_right\">7330</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">53</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">5855</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">54</td>\n<td headers=\"n\" class=\"gt_row gt_right\">2922</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">55</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">3684</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">56</td>\n<td headers=\"n\" class=\"gt_row gt_right\">735</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">57</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">7340</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">58</td>\n<td headers=\"n\" class=\"gt_row gt_right\">2201</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">59</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">7318</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">60</td>\n<td headers=\"n\" class=\"gt_row gt_right\">2194</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">61</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">2951</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">62</td>\n<td headers=\"n\" class=\"gt_row gt_right\">5878</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">63</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">5143</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">64</td>\n<td headers=\"n\" class=\"gt_row gt_right\">5115</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">65</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">3657</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">66</td>\n<td headers=\"n\" class=\"gt_row gt_right\">737</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">67</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">4391</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">68</td>\n<td headers=\"n\" class=\"gt_row gt_right\">6582</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">70</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">1461</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">72</td>\n<td headers=\"n\" class=\"gt_row gt_right\">8</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">73</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">2939</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">75</td>\n<td headers=\"n\" class=\"gt_row gt_right\">1463</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">76</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">1472</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">77</td>\n<td headers=\"n\" class=\"gt_row gt_right\">753</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">78</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">2951</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">79</td>\n<td headers=\"n\" class=\"gt_row gt_right\">5118</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">80</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">11</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">81</td>\n<td headers=\"n\" class=\"gt_row gt_right\">1465</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">82</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">2926</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">83</td>\n<td headers=\"n\" class=\"gt_row gt_right\">4393</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">86</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">744</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">89</td>\n<td headers=\"n\" class=\"gt_row gt_right\">2929</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right gt_striped\">90</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">3652</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">91</td>\n<td headers=\"n\" class=\"gt_row gt_right\">2193</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nThe ages seem reasonable (calculated relative to the earliest date of transactions). There are a few thousand 17-year-olds, which is too young to have their own credit card, but it is plausible that they would be an authorized user on their parents' card. `age` seems a more reasonable variable than `dob`, so `dob` is also dropped from the dataset. For example, scammers might be more likely to target 90-year-olds. The age is the feature that leads to them being targeted, not the birth year. The birth year is related to age through the current date- in 10 years, a new cohort of birth years would be targeted if age is the important feature. So the `age` feature is more robust to passing time than `dob`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 18: Removing dob\n\nfraud <- fraud %>%\n  select(-dob)\n```\n:::\n\n\n## 5.4. Looking at the date-times\n\n**date-time**\n\n`trans_date_trans_time`, Transaction DateTime\n\n**Questions**\n\nWould processing the date-times yield more useful predictors?\n\nFirst, I want to look at variation in the number of transactions with date-time. I chose to use a histogram with bins corresponding to one month widths.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 19: Looking at Transaction Date/ Times\n\nggplot(fraud, aes(trans_date_trans_time)) +\n  geom_histogram(color = \"darkcyan\",\n                 fill = \"darkcyan\",\n                 bins = 24) + #24 months in dataset\n  ggtitle(\"Figure 7: When do Transactions occur\") +\n  ylab(\"Count\") +\n  xlab(\"Date/ Time\")\n```\n\n::: {.cell-output-display}\n![](fraud_tutorial_files/figure-html/date-times-viz-1.png){width=672}\n:::\n:::\n\n\nNext, I will break the transaction date-time into day of the week, hour, and the date only. I'm doing this here with [lubridate functions](https://lubridate.tidyverse.org/), but I could also do this in the model building section, when I create recipes by using [step_date()](https://recipes.tidymodels.org/reference/step_date.html). I will also graph transactions by day of the week.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# |label: day-transactions\n# Code Block 20: \n\nfraud <- fraud %>%\n  mutate(\n    date_only = date(trans_date_trans_time),\n    hour = hour(trans_date_trans_time),\n    weekday = wday(trans_date_trans_time)\n  )\n\nggplot(fraud, aes(weekday)) +\n  geom_histogram(\n    color = \"darkcyan\",\n    fill = \"darkcyan\",\n    binwidth = 1,\n    center = 0.5\n  ) +\n  ggtitle(\"Figure 7: On what days do transactions occur?\") +\n  ylab(\"Count\") +\n  xlab(\"Weekday\")\n```\n\n::: {.cell-output-display}\n![](fraud_tutorial_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nMonday has the highest number of transactions; this could be due to businesses processing orders that came in over the weekend. By default, lubridate codes the day of the week as a number where 1 means Monday, 7 means Sunday.\n\nNow, I look at what time of day do most transactions occur?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 21: What time do transactions occur\nfig_8a <- ggplot(fraud, aes(hour)) +\n  geom_boxplot(color = \"darkcyan\") +\n  #ggtitle(\"What hour do transactions occur\") +\n  ylab(\"Count\") +\n  xlab(\"Hour\")\n\n\nfig_8b <- ggplot(fraud, aes(hour)) +\n  geom_bar(fill = \"darkcyan\") +\n  #ggtitle(\"What hour do transactions occur\") +\n  ylab(\"Count\") +\n  xlab(\"Hour\") \n\nplot_fig_8 <- plot_grid(fig_8a, fig_8b, labels = c('A', 'B'))\n\ntitle_8 <- ggdraw() +\n  draw_label(\n    \"Figure 8. When do transactions occur?\",\n    fontface = 'bold',\n    x = 0,\n    hjust = 0\n  ) +\n  theme(\n    plot.margin = margin(0, 0, 0, 7))\nplot_grid(title_8,\n          plot_fig_8,\n          ncol = 1,\n          # rel_heights values control vertical title margins\n          rel_heights = c(0.1, 1))\n```\n\n::: {.cell-output-display}\n![](fraud_tutorial_files/figure-html/hour-transactions-graph-1.png){width=672}\n:::\n:::\n\n\nThis data honestly looks funny to me. I might expect that most transactions would occur during normal business hours (\\~9-5) or more occur during lunch or after work, but what we see is a lower number of transactions from midnight to \\~ 2 pm and then a higher number of transactions from 2 pm until midnight. The odd pattern could be a sign that something is wrong with the data (perhaps timezones aren't being encoded properly?), or it could be simply a lack of subject matter knowledge (for example, transactions are pre-authorized at the time of sale and processed later, and the transaction time is the processing time, not the sale time.) Of course, this is also a synthetic dataset, so this pattern may be simply the result of user input choices when the set was generated. If this were a real dataset, I'd chase this down.\n\nAnd I made a table too, just to look at this data in another way.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 22:\ntable_5_data <- fraud %>% count(hour)\n\ntable_5 <- table_5_data %>%\n  gt() %>%\n  tab_header(title = \"Transactions by Time of Day\") %>%\n  cols_label(hour = \"Hour\", n = \"Count\") %>%\n  opt_stylize(style = 1,\n              color = \"green\",\n              add_row_striping = TRUE)\ngt:::as.tags.gt_tbl(table_5)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"wilmsaxovz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wilmsaxovz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wilmsaxovz thead, #wilmsaxovz tbody, #wilmsaxovz tfoot, #wilmsaxovz tr, #wilmsaxovz td, #wilmsaxovz th {\n  border-style: none;\n}\n\n#wilmsaxovz p {\n  margin: 0;\n  padding: 0;\n}\n\n#wilmsaxovz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #027101;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #027101;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wilmsaxovz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wilmsaxovz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wilmsaxovz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wilmsaxovz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wilmsaxovz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #038901;\n}\n\n#wilmsaxovz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #038901;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #038901;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wilmsaxovz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wilmsaxovz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wilmsaxovz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wilmsaxovz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wilmsaxovz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #038901;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wilmsaxovz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wilmsaxovz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #038901;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #038901;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wilmsaxovz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #038901;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #038901;\n  vertical-align: middle;\n}\n\n#wilmsaxovz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wilmsaxovz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wilmsaxovz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: none;\n  border-top-width: 1px;\n  border-top-color: #CAFFAF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #CAFFAF;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #CAFFAF;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wilmsaxovz .gt_stub {\n  color: #FFFFFF;\n  background-color: #038901;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #038901;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wilmsaxovz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wilmsaxovz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wilmsaxovz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wilmsaxovz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wilmsaxovz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #038901;\n}\n\n#wilmsaxovz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wilmsaxovz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #038901;\n}\n\n#wilmsaxovz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #CAFFAF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wilmsaxovz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #038901;\n}\n\n#wilmsaxovz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #038901;\n}\n\n#wilmsaxovz .gt_striped {\n  background-color: #F4F4F4;\n}\n\n#wilmsaxovz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #038901;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #038901;\n}\n\n#wilmsaxovz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wilmsaxovz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wilmsaxovz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wilmsaxovz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wilmsaxovz .gt_left {\n  text-align: left;\n}\n\n#wilmsaxovz .gt_center {\n  text-align: center;\n}\n\n#wilmsaxovz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wilmsaxovz .gt_font_normal {\n  font-weight: normal;\n}\n\n#wilmsaxovz .gt_font_bold {\n  font-weight: bold;\n}\n\n#wilmsaxovz .gt_font_italic {\n  font-style: italic;\n}\n\n#wilmsaxovz .gt_super {\n  font-size: 65%;\n}\n\n#wilmsaxovz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wilmsaxovz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wilmsaxovz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wilmsaxovz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wilmsaxovz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wilmsaxovz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wilmsaxovz .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Transactions by Time of Day</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Hour\">Hour</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Count\">Count</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"hour\" class=\"gt_row gt_right\">0</td>\n<td headers=\"n\" class=\"gt_row gt_right\">11039</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right gt_striped\">1</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">11241</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right\">2</td>\n<td headers=\"n\" class=\"gt_row gt_right\">11019</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right gt_striped\">3</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">11227</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right\">4</td>\n<td headers=\"n\" class=\"gt_row gt_right\">10904</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right gt_striped\">5</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">11023</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right\">6</td>\n<td headers=\"n\" class=\"gt_row gt_right\">11145</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right gt_striped\">7</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">11094</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right\">8</td>\n<td headers=\"n\" class=\"gt_row gt_right\">11123</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right gt_striped\">9</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">10997</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right\">10</td>\n<td headers=\"n\" class=\"gt_row gt_right\">11123</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right gt_striped\">11</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">11016</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right\">12</td>\n<td headers=\"n\" class=\"gt_row gt_right\">17168</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right gt_striped\">13</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">17125</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right\">14</td>\n<td headers=\"n\" class=\"gt_row gt_right\">16879</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right gt_striped\">15</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">17169</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right\">16</td>\n<td headers=\"n\" class=\"gt_row gt_right\">17465</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right gt_striped\">17</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">17011</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right\">18</td>\n<td headers=\"n\" class=\"gt_row gt_right\">17021</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right gt_striped\">19</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">17277</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right\">20</td>\n<td headers=\"n\" class=\"gt_row gt_right\">17298</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right gt_striped\">21</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">17267</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right\">22</td>\n<td headers=\"n\" class=\"gt_row gt_right\">17460</td></tr>\n    <tr><td headers=\"hour\" class=\"gt_row gt_right gt_striped\">23</td>\n<td headers=\"n\" class=\"gt_row gt_right gt_striped\">17516</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nStill weird.\n\nI discard the original variable and keep the new variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 23:\n#removing the original variable and keeping the component variables.\nfraud <- fraud %>%\n  select(-trans_date_trans_time)\n```\n:::\n\n\n## 5.5. Looking at the numerical variables\n\n**Numerical**\n\n`amt`, transaction amount\n\n**Questions**\n\nWould transforming this data produce a more normal distribution?\n\nGenerally, more normal or at least more symmetric data tends to be fitted better, especially when using model-fitting algorithms that arise from statistics rather than pure machine learning.\n\nI compare the original data with the log-transformed data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 24:\nfig_9a <- ggplot(fraud, aes(amt)) +\n  geom_histogram(color = \"darkcyan\", fill = \"darkcyan\", bins = 50) +\n  #ggtitle(\"Amount of Transaction\") +\n  ylab(\"Count\") +\n  xlab(\"purchase amount ($)\")\n\nfig_9b <- ggplot(fraud, aes(log(amt))) +\n  geom_histogram(color = \"darkcyan\", fill = \"darkcyan\", bins = 50) +\n  #ggtitle(\"log(Amount) of Transaction\") +\n  ylab(\"Count\") +\n  xlab(\"log(purchase amount) ($)\")\n\nplot_fig_9 <-\n  plot_grid(fig_9a, fig_9b, labels = c('A', 'B'), label_size = 12)\ntitle_9 <- ggdraw() +\n  draw_label(\n    \"Figure 9. Distribution of amount and log(amount)\",\n    fontface = 'bold',\n    x = 0,\n    hjust = 0\n  ) +\n  theme(\n    plot.margin = margin(0, 0, 0, 7))\nplot_grid(title_9,\n          plot_fig_9,\n          ncol = 1,\n          rel_heights = c(0.1, 1))\n```\n\n::: {.cell-output-display}\n![](fraud_tutorial_files/figure-html/amt-log-amt-graph-1.png){width=672}\n:::\n:::\n\n\nThe transformed data is more symmetric so that the transformed variable will be retained.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 25:\nfraud <- fraud %>%\n  mutate(amt_log = log(amt))\n```\n:::\n\n\nI do a final clean-up of variables next. I remove some variables that I don't think will impact fraud- the population of the home city and the location of the home. I don't think the home should have an impact on fraud; it is where the card is used, not where it is billed, that should matter. I suppose you could have a neighborhood where all the mail was being stolen, and cards were compromised that way, but I think most cards get compromised at the point of sale.\n\nI also removed the date. The date itself is unlikely to be related to fraud. It is possible that special dates are correlated with fraud, like a holiday or a big sports match. Engineering a holiday feature could be a future improvement.\n\nThere is a possibility that job type could have an impact on fraud; for example, a trucker might be more likely to have his/her card stolen just because they are always on the road and visiting a wide variety of places where they would use the card. Or this could come in as an interaction term with distance; distance from home and the occupation trucker might have no correlation, but the distance from home and the occupation teacher might have because it would be a more unusual event for that `job`. However, some model fitting fails to converge when `job` is included, and it takes a long time for the models that it does work for. So I remove it too.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 26:\n# removed in related clusters, so easy to comment out if you want to add back a group\n\n# remove amt and keep log transformed version\nfraud <- fraud %>%\n  select(-amt)\n\n# home location and home city pop shouldn't impact fraud\nfraud <- fraud %>%\n  select(-city_pop,-lat_home,-long_home)\n\n# remove date\nfraud <- fraud %>% select(-date_only)\n\n# remove jobs\nfraud <- fraud %>%\n  select(-job)  \n```\n:::\n\n\n# 6. Final preparation for modeling\n\nNext, I plot the correlation plot for the dataset. Highly correlated variables can cause problems for some fitting algorithms, again, especially for those coming from statistics. It also gives you a bit of a feel for what might come out of the model fitting. This is also a chance to do one last fact-check. For example, `category` and `amt` are reasonably correlated. The sign isn't particularly important in this case since `category` is arbitrarily ordered.\n\nI like the corrplot package for making correlation plots. I think this package produces very nice visualizations. I did find that the title sometimes gets cut off and I found the solution was to add some margin as explained [here](https://stefaneng.github.io/corrplot-title-cut-off/).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Code Block 27: examining correlation between variables \n\nfraud %>%\n  mutate_if(is.factor, as.numeric) %>%\n  dplyr::select(is_fraud, everything()) %>%\n  cor %>%\n  {\n    .[order(abs(.[, 1]), decreasing = TRUE),\n      order(abs(.[, 1]), decreasing = TRUE)]\n  } %>%\n  corrplot(\n    type = 'lower',\n    tl.col = 'black',\n    addCoef.col = 'black',\n    cl.ratio = 0.2,\n    tl.srt = 45,\n    col = COL2('PuOr', 10),\n    diag = FALSE ,\n    mar = c(0, 0, 2, 0),\n    title = \"Figure 10: Correlations between fraud and the predictors\"\n  )\n```\n\n::: {.cell-output-display}\n![](fraud_tutorial_files/figure-html/correlation-graph-1.png){width=672}\n:::\n:::\n\n\nTidymodels requires that the outcome be a factor and the [positive class be the first level](https://community.rstudio.com/t/tidymodels-which-factor-level-is-the-default-positive-class/100428). So I create the factor and relevel it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 28: \n\n# in tidymodels, outcome should be a factor\nfraud$is_fraud <- factor(fraud$is_fraud)\nlevels(fraud$is_fraud)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"0\" \"1\"\n```\n:::\n\n```{.r .cell-code}\n# first level is the event in tidymodels, so we need to reorder\nfraud$is_fraud <- relevel(fraud$is_fraud, ref = \"1\")\nlevels(fraud$is_fraud)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"1\" \"0\"\n```\n:::\n:::\n\n\nAnd take one last look at the data and make sure I have the variables I expect. I also export this processed data for use in [my tidymodels tutorial](https://lsinks.github.io/posts/2023-04-10-tidymodels/tidymodels_tutorial.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 29: Viewing Final Fraud Dataset\nglimpse(fraud)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 339,607\nColumns: 9\n$ category       <fct> grocery_pos, entertainment, grocery_pos, shopping_pos, …\n$ lat_trans      <dbl> 48.8878, 42.1808, 41.6125, 32.9396, 43.0172, 20.0827, 4…\n$ long_trans     <dbl> -118.2105, -112.2620, -122.5258, -105.8189, -111.0292, …\n$ is_fraud       <fct> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ distance_miles <dbl> 1271.5119381, 0.9433129, 2.3078189, 0.8747466, 2.499453…\n$ age            <dbl> 40, 56, 73, 51, 51, 52, 73, 57, 31, 34, 42, 31, 63, 44,…\n$ hour           <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1…\n$ weekday        <dbl> 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3…\n$ amt_log        <dbl> 4.6749761, 5.3941274, 4.5673645, 2.0502702, 1.9242487, …\n```\n:::\n\n```{.r .cell-code}\n# save file to use in other tutorial\n#saveRDS(fraud, file = \"fraud_processed.RDS\")\n```\n:::\n\n\n# 7. Finding a high performing model\n\nI'm planning to study the following models and methods of handling imbalanced class problems.\n\nExplore different classification models\n\n1.  logistic regression\n\n2.  elastic net logistic regression\n\n3.  lightgbm\n\n4.  random forest\n\nExplore different method of handling imbalanced class problems\n\n1.  do nothing\n\n2.  SMOTE\n\n3.  ROSE\n\n4.  downsample\n\nThis ends up being 4 x 4 different fits, and keeping track of all the combinations can become difficult. Luckily, tidymodels has a function workflow_set that will create all the combinations and workflow_map to run all the fitting procedures.\n\n## 7.1. Splitting the data\n\nFirst, preparation work. Here, I split the data into a testing and training set. I also create folds for cross-validation from the training set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 30 : Train/Test Splits & CV Folds \n\n# Split the data into a test and training set\nset.seed(222)\ndata_split <-\n  initial_split(fraud, prop = 0.75, strata = is_fraud)\n\n# Create data frames for the two sets:\ntrain_data <- training(data_split)\ntest_data  <- testing(data_split)\n\nstart_time <- Sys.time()\n\nset.seed(123)\nfraud_folds <- vfold_cv(train_data, v = 3, strata = is_fraud)\n```\n:::\n\n\n## 7.2. Creating recipes\n\nNext, I create recipes that do preprocessing of the data- making dummy variables, normalizing, and removing variables that only contain one value (`step_zv(all_predictors())`). The processing will be applied to both the training and testing data as you move through the workflow.\n\nI used the chart found in [Appendix A](https://www.tmwr.org/pre-proc-table.html) of the Tidy Modeling with R by Max Kuhn and Julia Silge to choose the preprocessing of data. Some models require specific types of preprocessing, others don't require it, but it can produce better or faster fitting, and in other cases, the preprocessing isn't required and probably doesn't help. The chart breaks this down for each category of preprocessing model by model. The same preprocessing steps were required or recommended for the models I chose, so I used them across the board. You can create recipes for different models and build a workflow manually to match the models to the proper recipe. This process is covered extensively in [Chapter 15](https://www.tmwr.org/workflow-sets.html) of Tidy Modeling with R.\n\nI use the selector functions (`all_nominal_predictors()`, `all_numerical_predictors()`, etc.) available in the tidymodels framework. A listing of all selector functions usable in tidymodels can be found [here](https://recipes.tidymodels.org/reference/selections.htm). Using selector functions when handling groups of features reduces the chance of mistakes and typos.\n\nI then modify this recipe to handle the imbalanced class problem. I use SMOTE and ROSE hybrid methods to balance the classes. These methods create synthetic data for the minority class and downsample the majority class to balance the classes. I also use downsample, which throws away majority class records to balance the two classes. A good overview is [here](https://www.r-bloggers.com/2019/04/methods-for-dealing-with-imbalanced-data/), and it also provides a tutorial for handling this type of problem with caret, rather than tidymodels. These recipe steps require the [themis package](https://cran.r-project.org/web/packages/themis/index.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 31: creating recipes\n\nrecipe_plain <-\n  recipe(is_fraud ~ ., data = train_data) %>%\n  step_dummy(all_nominal_predictors()) %>%\n  step_normalize(all_numeric_predictors()) %>%\n  step_zv(all_predictors())\n\nrecipe_rose <-\n  recipe_plain %>%\n  step_rose(is_fraud)\n\nrecipe_smote <-\n  recipe_plain %>%\n  step_smote(is_fraud)\n\nrecipe_down <-\n  recipe_plain %>%\n  step_downsample(is_fraud)\n```\n:::\n\n\n## 7.3. Setting the model engines\n\nNext, I set the engines for the models. I tune the hyperparameters of the elastic net logistic regression and the lightgbm. Random Forest also has tuning parameters, but the random forest model is pretty slow to fit, and adding tuning parameters makes it even slower. If none of the other models worked well, then tuning RF would be a good idea.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 32: Setting engines\n\n#this is the standard logistic regression\nlogreg_spec <-\n  logistic_reg() %>%\n  set_engine(\"glm\")\n\n#elastic net regularization of logistic regression\n#this has 2 hyperparameters that we will tune\nglmnet_spec <-\n  logistic_reg(penalty = tune(),\n               mixture = tune()) %>%\n  set_engine(\"glmnet\")\n\n#random forest also has tunable hyperparameters, but we won't\nrf_spec <-\n  rand_forest(trees = 100) %>%\n  set_engine(\"ranger\") %>%\n  set_mode(\"classification\")\n\n#This is a boosted gradient method with 6 tuning parameters\nlightgbm_spec <-\n  boost_tree(\n    mtry = tune(),\n    trees = tune(),\n    tree_depth = tune(),\n    learn_rate = tune(),\n    min_n = tune(),\n    loss_reduction = tune()\n  ) %>%\n  set_engine(engine = \"lightgbm\") %>%\n  set_mode(mode = \"classification\")\n```\n:::\n\n\n## 7.4. Creating a metrics set\n\nLastly, I create a metrics set in Code Block 33. Accuracy is generally a terrible metric for highly imbalanced problems; the model can achieve high accuracy by assigning everything to the majority class. Alternate metrics like [sensitivity](https://en.wikipedia.org/wiki/Sensitivity_and_specificity) or [j-index](https://en.wikipedia.org/wiki/Youden%27s_J_statistic) are better choices for the imbalanced class situation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 33: Setting Metrics\n\nfraud_metrics <-\n  metric_set(roc_auc, accuracy, sensitivity, specificity, j_index)\n```\n:::\n\n\n## 7.5. Creating the workflow_set\n\nNext, I create the workflow_set. This is where tidymodels shines. I feed it the 4 recipes and the 4 engines, and it makes all the permutations to fit. (As I mentioned earlier, you can manually create a workflow_set where you assign specific recipes to specific models, but here all recipes work with all models.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code block 34:\nwf_set_tune <-\n  workflow_set(\n    list(plain = recipe_plain,\n         # rose = recipe_rose,\n         # smote = recipe_smote,\n         down = recipe_down),\n    list(glmnet = glmnet_spec,\n      lightgmb = lightgbm_spec,\n      #rf = rf_spec,\n      logreg = logreg_spec\n     )\n  )\n```\n:::\n\n\n## 7.6. Fitting all the models\n\nI now run these 16 models. I pass `workflow_map()` the workflow_set from Code Block 34. The next parameter is what type of fitting you want to do. Here, I used `tune_grid` and had it generate 6 grid points. For the models that don't require hyperparameter tuning, the function defaults to `fit_resamples` instead. The acceptable types of fitting functions are found [here](https://workflowsets.tidymodels.org/reference/workflow_map.html). It is important to note that you can only use fitting methods that operate on folds; you cannot pass `workflow_map()` the entire train or test set and have it work.\n\nI'm using the verbose option when fitting. This shows how long each model takes. When I first started, I had no idea how long various models would take. I'm running this on an older, low-end laptop (Intel(R) Core(TM) i5-7200U CPU \\@ 2.50GHz 2.71 GHz, 32 GB RAM).\n\nI would recommend 10 folds rather than 3 if you have the time. Similarly, 6 grids points is a very low number.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code block 35: \nset.seed(345)\ntune_results <-\n  workflow_map(\n    wf_set_tune,\n    \"tune_grid\",\n    resamples = fraud_folds,\n    grid = 3,\n    metrics = fraud_metrics,\n    verbose = TRUE\n    )\n```\n\n::: {.cell-output .cell-output-stderr}\n```\ni 1 of 6 tuning:     plain_glmnet\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ 1 of 6 tuning:     plain_glmnet (1m 14.9s)\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\ni 2 of 6 tuning:     plain_lightgmb\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\ni Creating pre-processing data to finalize unknown parameter: mtry\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ 2 of 6 tuning:     plain_lightgmb (2m 24.5s)\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\ni\tNo tuning parameters. `fit_resamples()` will be attempted\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\ni 3 of 6 resampling: plain_logreg\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ 3 of 6 resampling: plain_logreg (10.6s)\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\ni 4 of 6 tuning:     down_glmnet\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ 4 of 6 tuning:     down_glmnet (6.4s)\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\ni 5 of 6 tuning:     down_lightgmb\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\ni Creating pre-processing data to finalize unknown parameter: mtry\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ 5 of 6 tuning:     down_lightgmb (1m 48.9s)\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\ni\tNo tuning parameters. `fit_resamples()` will be attempted\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\ni 6 of 6 resampling: down_logreg\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ 6 of 6 resampling: down_logreg (2.8s)\n```\n:::\n:::\n\n\n## 7.7. Evaluating the models\n\nI viewed the results of the fitting as both a table (Code Block 36) and graphically using `autoplot()`. The default autoplot legend is unclear, so you'll want to do both, as I did. The legend doesn't label by recipe (only that a recipe was used for preprocessing) and folds related categories into one. Here you see that elastic net logistic regression and logistic regression are both labeled log_reg.\n\nThe object we have now, `tune_results`, is incredibly large and complicated. Using View() on it has crashed RStudio for me. This object should be interacted with through helper functions. For more information about this, please see my [other tutorial on tidymodels](https://lsinks.github.io/posts/2023-04-10-tidymodels/tidymodels_tutorial.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|label: rank-results-table\n# Code Block 35\nrank_results(tune_results, rank_metric = \"j_index\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 70 × 9\n   wflow_id      .config    .metric  mean std_err     n preprocessor model  rank\n   <chr>         <chr>      <chr>   <dbl>   <dbl> <int> <chr>        <chr> <int>\n 1 down_lightgmb Preproces… accura… 0.951 0.00267     3 recipe       boos…     1\n 2 down_lightgmb Preproces… j_index 0.903 0.00558     3 recipe       boos…     1\n 3 down_lightgmb Preproces… roc_auc 0.989 0.00211     3 recipe       boos…     1\n 4 down_lightgmb Preproces… sensit… 0.952 0.00614     3 recipe       boos…     1\n 5 down_lightgmb Preproces… specif… 0.951 0.00269     3 recipe       boos…     1\n 6 down_lightgmb Preproces… accura… 0.937 0.00383     3 recipe       boos…     2\n 7 down_lightgmb Preproces… j_index 0.860 0.0132      3 recipe       boos…     2\n 8 down_lightgmb Preproces… roc_auc 0.982 0.00259     3 recipe       boos…     2\n 9 down_lightgmb Preproces… sensit… 0.923 0.00947     3 recipe       boos…     2\n10 down_lightgmb Preproces… specif… 0.937 0.00381     3 recipe       boos…     2\n# ℹ 60 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 36\nautoplot(tune_results, rank_metric = \"j_index\", select_best = TRUE) +\n  ggtitle(\"Figure 11: Performance of various models\")\n```\n\n::: {.cell-output-display}\n![](fraud_tutorial_files/figure-html/rank-results-table-1.png){width=672}\n:::\n:::\n\n\nThe best performing model / recipe pair by j-index is the downsampled lightgmb (`down_lightgmb`).\n\nTo see how this model/recipe performs across tuning parameters, we can use `extract_workflow_set_result` and `autoplot`. If you wanted to refine the hyperparameters more, you could use these results to narrow the search parameters to areas with the best performance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code block 37: \n\nresults_down_gmb <- tune_results %>%\n  extract_workflow_set_result(\"down_lightgmb\")\nautoplot(results_down_gmb) +\n  theme_pander(8) +\n  ggtitle(\"Figure 12: Perfomance of different hyperparameters\")\n```\n\n::: {.cell-output-display}\n![](fraud_tutorial_files/figure-html/gmb-hyperparameters-1.png){width=672}\n:::\n:::\n\n\nIn this case, I'm just going to extract the best set of hyperparameters and move on. This is done using the `extract_workflow_set_result` and `select_best(metric = \"j_index\")`. There are other ways to select the best hyperparameters. The list of selectors is found [here](https://tune.tidymodels.org/reference/show_best.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code block 38: \nbest_hyperparameters <- tune_results %>%\n  extract_workflow_set_result(\"down_lightgmb\") %>%\n  select_best(metric = \"j_index\")\n```\n:::\n\n\nAnd here I look at the selected hyperparameters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code block 39: \nprint(best_hyperparameters)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 7\n   mtry trees min_n tree_depth  learn_rate loss_reduction .config             \n  <int> <int> <int>      <int>       <dbl>          <dbl> <chr>               \n1     9  1255     3          7 0.000000608  0.00000000404 Preprocessor1_Model2\n```\n:::\n:::\n\n\nNow, I am going to use the convenience functions finalize_workflow() and last_fit() to add [the best hyperparameters to the workflow](https://tune.tidymodels.org/reference/finalize_model.html), [train the model/recipe on the entire training set, and then predict on the entire test set](https://tune.tidymodels.org/reference/last_fit.html). There is a lot of stuff going on here at once (Code Block 40)!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 40: Validating the model with the test data\nvalidation_results <- tune_results %>%\n  extract_workflow(\"down_lightgmb\") %>%\n  finalize_workflow(best_hyperparameters) %>%\n  last_fit(split =  data_split, metrics = fraud_metrics)\n```\n:::\n\n\nLastly, I look at the metrics and ROC curve for the test data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Code Block 41: Looking at the validation metrics from the test data.\ncollect_metrics(validation_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 4\n  .metric     .estimator .estimate .config             \n  <chr>       <chr>          <dbl> <chr>               \n1 accuracy    binary         0.959 Preprocessor1_Model1\n2 sensitivity binary         0.934 Preprocessor1_Model1\n3 specificity binary         0.959 Preprocessor1_Model1\n4 j_index     binary         0.893 Preprocessor1_Model1\n5 roc_auc     binary         0.984 Preprocessor1_Model1\n```\n:::\n\n```{.r .cell-code}\nvalidation_results %>%\n  collect_predictions() %>%\n  roc_curve(is_fraud, .pred_1) %>%\n  autoplot() +\n  ggtitle(\"Figure 13: ROC Curve\")\n```\n\n::: {.cell-output-display}\n![](fraud_tutorial_files/figure-html/model-performance-1.png){width=672}\n:::\n:::\n\n\nJust for fun, let's see how much money this model would have save our credit card company. I'm going to assume the cost of fraud is the cost of the transaction. I calculate the total cost of all the fraudulent transactions in the test dataset. I then calculate the cost based on the model predictions. Any truly fraudulent transactions that were not caught, cost the value of the transaction. Legitimate transactions that were marked as fraud were assigned \\$0 cost. This likely isn't true. There is the cost of having to deal with customers calling because the transaction was declined or the cost sending out texts for suspicious transactions, but this cost is very small relative to the cost of a fraudulent transaction. I got the idea from this paper: Zhang, D. , Bhandari, B. and Black, D. (2020) Credit Card Fraud Detection Using Weighted Support Vector Machine. *Applied Mathematics*, **11**, 1275-1291. doi: [10.4236/am.2020.1112087](https://doi.org/10.4236/am.2020.1112087).\n\nI'm using the list method to access predictions, but you could also use `collect_predictions()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#code block 42: Calculating how much fraud cost the company\n\nval <- validation_results[[5]][[1]]\n\nval %>% conf_mat(truth = is_fraud, estimate = .pred_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          Truth\nPrediction     1     0\n         1   428  3467\n         0    30 80977\n```\n:::\n\n```{.r .cell-code}\nval <-\n  #I'm going to bind this to the test data and I want unique names\n  val %>% rename(is_fraud2  = is_fraud) \n\ncost <- test_data %>%\n  cbind(val)\n\ncost <- cost %>%\n  select(is_fraud, amt_log, pred = .pred_class, is_fraud2) \n\ncost <- cost %>%\n  #cost for missing fraud in prediction\n  mutate(cost_act = ifelse((is_fraud == 1 &\n                              pred == 0), amt_log, 0)) %>%\n  #cost of all fraud\n  mutate(cost_potential = ifelse((is_fraud == 1), amt_log, 0))\n\nmissed_fraud_cost <- round(sum(exp(cost$cost_act)), 2)\nall_fraud_cost <- round(sum(exp(cost$cost_potential)), 2)\n\nsavings <- 100 * round((sum(exp(cost$cost_act)) / sum(exp(cost$cost_potential))), 2)\n```\n:::\n\n\nMy model had dramatic costs savings for the imaginary credit card company! The total dollar cost of all the fraudulent transactions is 3.207071\\times 10^{5}, while the value of the missed fraud cases was 8.58126\\times 10^{4}. The losses from the model were 27 % of the potential losses.\n",
    "supporting": [
      "fraud_tutorial_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}