{
  "hash": "e27f77b610f0b70c4c3fcd30f75f271f",
  "result": {
    "markdown": "---\ntitle: \"TidyTuesday Week 25: UFO Sightings Redux\"\ndescription: \"TidyTuesday: UFO Sightings\"\ntwitter-card:\n  image: \"thumbnail.png\"\nauthor:\n  - name: Louise E. Sinks\n    url: https://lsinks.github.io/\ndate: 06-20-2023\ncategories: [R, TidyTuesday, R-code, Code-Along, Data-Viz] # self-defined categories\ncitation:\n  url: https://lsinks.github.io/posts/2023-06-19-tidytuesday-UFOs\nimage: \"thumbnail.png\"\ndraft: true # setting this to `true` will prevent your post from appearing on your listing page until you're ready!\n---\n\n\nI haven't been TidyTuesdaying because I've been learning Tableau. I'll write more about that later; but it has been an interesting experience and provides different perspectives on data compared to what you might get from R. (I'm sure you could reproduce everything in Tableau in R and vice versa, but it is certainly easier to perform certain actions in one program over the other.)\n\nToday's [TidyTuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-06-20/readme.md) is based on a dataset about the UFO sightings. This is an updated version of a tidytuesday challenge from 2019. The readme suggests that differences between the two datasets might be especially interesting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(skimr)\nlibrary(tidyverse)\nlibrary(ggthemes)\n```\n:::\n\n\nLoad the data with the TidyTuesday package in the usual way.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntuesdata <- tidytuesdayR::tt_load(2023, week = 25)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n--- Compiling #TidyTuesday Information for 2023-06-20 ----\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n--- There are 3 files available ---\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n--- Starting Download ---\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tDownloading file 1 of 3: `ufo_sightings.csv`\n\tDownloading file 2 of 3: `places.csv`\n\tDownloading file 3 of 3: `day_parts_map.csv`\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n--- Download complete ---\n```\n:::\n\n```{.r .cell-code}\nufo_sightings <- tuesdata$`ufo_sightings`\nplaces <- tuesdata$`places`\nday_parts_map <- tuesdata$`day_parts_map`\n```\n:::\n\n\nThis dataset combines information about reported UFO sightings with information about the lighting conditions at that time from sunrise-sunset. That is, was it day time, night time, twilight, etc. when the sighting occurred. This is an augmentation of the original dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(ufo_sightings)\n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |              |\n|:------------------------|:-------------|\n|Name                     |ufo_sightings |\n|Number of rows           |96429         |\n|Number of columns        |12            |\n|_______________________  |              |\n|Column type frequency:   |              |\n|character                |7             |\n|Date                     |1             |\n|logical                  |1             |\n|numeric                  |1             |\n|POSIXct                  |2             |\n|________________________ |              |\n|Group variables          |None          |\n\n\n**Variable type: character**\n\n|skim_variable     | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-----------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|city              |         0|          1.00|   3|  26|     0|    10721|          0|\n|state             |        85|          1.00|   2|  31|     0|      684|          0|\n|country_code      |         0|          1.00|   2|   2|     0|      152|          0|\n|shape             |      2039|          0.98|   3|   9|     0|       24|          0|\n|reported_duration |         0|          1.00|   2|  25|     0|     4956|          0|\n|summary           |        31|          1.00|   1| 135|     0|    95898|          0|\n|day_part          |      2563|          0.97|   5|  17|     0|        9|          0|\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|posted_date   |         0|             1|1998-03-07 |2023-05-19 |2012-08-19 |      619|\n\n\n**Variable type: logical**\n\n|skim_variable | n_missing| complete_rate| mean|count      |\n|:-------------|---------:|-------------:|----:|:----------|\n|has_images    |         0|             1|    0|FAL: 96429 |\n\n\n**Variable type: numeric**\n\n|skim_variable    | n_missing| complete_rate|     mean|      sd| p0| p25| p50| p75|       p100|hist  |\n|:----------------|---------:|-------------:|--------:|-------:|--:|---:|---:|---:|----------:|:-----|\n|duration_seconds |         0|             1| 31613.25| 6399774|  0|  30| 180| 600| 1987200000|▇▁▁▁▁ |\n\n\n**Variable type: POSIXct**\n\n|skim_variable          | n_missing| complete_rate|min        |max                 |median              | n_unique|\n|:----------------------|---------:|-------------:|:----------|:-------------------|:-------------------|--------:|\n|reported_date_time     |         0|             1|1925-12-29 |2023-05-18 19:27:00 |2012-02-05 03:00:00 |    86201|\n|reported_date_time_utc |         0|             1|1925-12-29 |2023-05-18 19:27:00 |2012-02-05 03:00:00 |    86201|\n:::\n:::\n\n\nThe data is fairly complete. The daypart is the least complete with only 97% completion. This variable is currently a string; it would be better as a factor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings$day_part <- as.factor(ufo_sightings$day_part)\n```\n:::\n\n\nNow we can see when it is most common to see UFOs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ufo_sightings, aes(day_part)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](UFOs_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThis is a pretty ugly plot. First, I'm going to clean up the formatting. The day-parts should be tilted so they are not overlapping, the axis labels are not clear, and I don't like the default ggplot theme. You need to change the plot theme before you tilt the axis labels, otherwise the theme's defaults will reset the axis label orientation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ufo_sightings, aes(day_part)) +\n  geom_bar() +\n  ylab(\"Number of Sighting\") +\n  xlab(\"\") +\n  theme_classic() +\n  theme(axis.text.x = element_text(angle = 45,hjust = 1)) \n```\n\n::: {.cell-output-display}\n![](UFOs_files/figure-html/prelim-plot-1.png){width=672}\n:::\n:::\n\n\nNow, there are two ways to order the bars. Usually, I'd use either ascending or descending order by count. But here, the day parts do have an intrinsic order- most light to least light (or the reverse) or something along the cycle. So, I need to order the factor day_part. I used the explanation [here](https://science.howstuffworks.com/nature/climate-weather/atmospheric/twilight-dusk.htm) get the order and decide on the color scale. I decided that afternoon was lighter than morning.\n\nFirst, I'll code the NAs as \"unknown\". It is a small percentage of the total data, so dropping them is also a defensible choice. It doesn't really impact the visualization to leave them in, and it does reveal some information about how detailed the reports are.\n\nI love the [POSIT cheatsheets for checking syntax](https://posit.co/resources/cheatsheets/), especially the printed pdfs because I annotate them with my own notes. However, they can end up out of date. Recently POSIT has created HTML versions and updated most of the pdfs. So if you have a printed forcats cheatsheet branded RStudio, go get the [new POSIT's one](https://rstudio.github.io/cheatsheets/factors.pdf), since some of the functions on the old cheatsheet are deprecated.\n\nTo convert NAs to a named level, the current function is `fct_na_value_to_level` rather than `fct_explicit_na` and the level is specified with `level = \"blah\"` rather than `na_level = \"blah\"`. Both ways are shown in the code block and both will work.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# old way of converting NAs to a specific level\n#ufo_sightings$day_part <- fct_explicit_na(ufo_sightings$day_part, na_level = #\"unknown\")\n\n# new way of converting NAs to a specific level\nufo_sightings$day_part <- fct_na_value_to_level(ufo_sightings$day_part, level = \"unknown\")\n```\n:::\n\n\nNow, I need to relevel the day_parts factor. I started with morning, and then progressed through the day_parts in the order they occur. I put the unknown level last.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings$day_part <- fct_relevel(ufo_sightings$day_part,c(\"morning\",\n                                      \"afternoon\", \"civil dusk\", \"nautical dusk\",\n                                      \"astronomical dusk\", \"night\",\n                                      \"astronomical dawn\", \"nautical dawn\",\n                                      \"civil dawn\", \"unknown\"))\n```\n:::\n\n\nNow, I'm going to use the aesthetic `fill = day_part` to color my bars by time of day. I'm also going to define a manual color scale in blues, grays, and blacks to reflect the state of the sky- light blues for daylight and darker blues/blacks for night times. I made the unknown green (for little green men). I played around with both colors and values to get a gradient that I liked. Note that both `gray` and `grey` work. I kept the legend on while I was adjusting the colors because it was easier to see the gradient as compared to looking at the bar chart, but I turned it off for the final graph.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ufo_sightings, aes(day_part, fill = day_part)) +\n  geom_bar() +\n  ylab(\"Number of Sighting\") +\n  xlab(\"\") +\n  theme_classic() +\n  theme(axis.text.x = element_text(angle = 45,hjust = 1)) +\n  scale_fill_manual(values = c(\"lightskyblue2\", \"lightskyblue1\", \"skyblue2\",\n \"skyblue3\",\"lightskyblue4\", \"grey23\",\"lightskyblue4\",\"skyblue3\",\"skyblue2\",\n \"green\")) +\n  ggtitle(\"When do UFO Sightings Occur?\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](UFOs_files/figure-html/final-graph-1.png){width=672}\n:::\n:::\n\n\nSo most sightings take place at night and very few take place in the early morning.\n\nThe sightings database also contains pictures of UFOs. Not all reports include pictures. It seems like it would be hard to get a good picture at night, so I'm wondering if most pictures are taken during daylight hours, despite having fewer over all sightings.\n\nhas_images is a boolean and the dataset is complete, but it seems that everything is coded FALSE? The [original dataset from 2019](https://github.com/rfordatascience/tidytuesday/blob/master/data/2019/2019-06-25/readme.md) doesn't include has_images, so I can't use that to repair most of the entries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings %>%\n  group_by(day_part) %>%\n  summarise(mean(has_images))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 2\n   day_part          `mean(has_images)`\n   <fct>                          <dbl>\n 1 morning                            0\n 2 afternoon                          0\n 3 civil dusk                         0\n 4 nautical dusk                      0\n 5 astronomical dusk                  0\n 6 night                              0\n 7 astronomical dawn                  0\n 8 nautical dawn                      0\n 9 civil dawn                         0\n10 unknown                            0\n```\n:::\n:::\n\n\nLooking at how the current dataset was prepared doesn't help much either. The data was rescraped from [National UFO Reporting Center](https://nuforc.org/) as shown [here](https://github.com/jonthegeek/apis/blob/main/01_ufo-data.qmd) and does not seem to include the original tidytuesday dataset at all. Searching for has_image, I find it first mentioned in line 890.\n\n`data_ufo_reports_clean <- data_ufo_reports_durations |>`\n\n`dplyr::mutate(`\n\n`state = dplyr::coalesce(state, ascii_state),`\n\n`# Recode \"images\" to TRUE/FALSE, and replace NAs while we're at it.`\n\n`has_images = isTRUE(images == \"Yes\"),`\n\nLooking at the saved scraped data, found [here](https://github.com/jonthegeek/apis/blob/main/data/data_ufo_reports.rds), there is an `images` column that contains \"Yes\" or NA. It is very incomplete, with a completion rate of 1%. I also looked at the final cleaned data (post encoding to TRUE/FALSE) and it only has FALSES. So, it looks like the re-coding might have gone wrong.\n\nHere is the original data from the scraping.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nurl <- \"https://github.com/jonthegeek/apis/raw/main/data/data_ufo_reports.rds\"\nufo_path <- withr::local_tempfile(fileext = \".rds\")\ndownload.file(url, ufo_path)\ndata_ufo_reports_1 <- readRDS(ufo_path)\n```\n:::\n\n\nSee how many images are in this dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_ufo_reports_1 %>%\n  filter(images == \"Yes\") %>%\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2342\n```\n:::\n:::\n\n\nThere are only 2342 images in the database. The raw scrapped data has 144451 rows, while our cleaned processed data has 96429 rows. So a fair number of data points were dropped. It is possible that all of the records with images were dropped during the cleaning and processing.\n\nI'm going to join the UFO dataset with the scrapped data. I'm letting R decide what columns to join on, but the join does need to include summary, since that is one column that certainly was not cleaned/ processed.\n\nThe place names were cleaned (see for example lines 277 and beyond in the cleaning code). When I do an inner_join, I only get 1881 records. I'd expect to get the 96429 records in the ufo_sightings data file, since they should be contained in the original larger dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined <- ufo_sightings %>%\n  inner_join(data_ufo_reports_1) \n```\n\n::: {.cell-output .cell-output-stderr}\n```\nJoining with `by = join_by(city, state, shape, summary)`\n```\n:::\n\n```{.r .cell-code}\ncombined %>%\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1881\n```\n:::\n:::\n\nIf I were working on this for something more mission critical, I'd dig through the cleaning code more carefully, and make sure it was all ok. For now, I'm just going to check the Boolean encoding step, using my much smaller combined dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# counting how many images\ncombined %>%\n  filter(images == \"Yes\") %>%\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18\n```\n:::\n\n```{.r .cell-code}\n#sthis is the re-coding step from the tidytuesday data\ncombined2 <- combined %>%\n  dplyr::mutate(\n       # Recode \"images\" to TRUE/FALSE, and replace NAs while we're at it.\n    has_images_tester = isTRUE(images == \"Yes\"))\n\n# counting how many images again\ncombined2 %>%\n  filter(images == \"Yes\") %>%\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18\n```\n:::\n\n```{.r .cell-code}\n# counting how many images after recode\ncombined2 %>%\n  filter(has_images_tester == TRUE) %>%\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nSo, the specified code clearly doesn't work. This is how I'd do it. I'd explicitly code both `TRUE` and `FALSE` using an `ifelse` clause in the mutate. Since the images contains a bunch of NAs, you need to be more careful about your test condition: `images == \"Yes\"` does give you the correct `TRUE`s, but it gives no `FALSE`s and retains all the NAs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined3 <- combined2 %>%\n  dplyr::mutate(\n       # Recode \"images\" to TRUE/FALSE, and replace NAs while we're at it.\n    has_images_correct1 = ifelse(images == \"Yes\", TRUE, FALSE))\n\ncombined3 %>%\n  filter(has_images_correct1 == TRUE) %>%\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18\n```\n:::\n\n```{.r .cell-code}\ncombined3 %>%\n  filter(has_images_correct1 == FALSE) %>%\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nThe better test condition for this dataset is to use `is.na(images) == FALSE` (or the reverse, it doesn't matter) and code `NA`s as `FALSE` and everything else as `TRUE`. This works because we have only have two values in the column (NA/ Yes). If you had other correct values, say Yes/ No/ NA, then this would not work. You'd need more complicated logic or two sets of `ifelse`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined4 <- combined3 %>%\n  dplyr::mutate(\n       # Recode \"images\" to TRUE/FALSE, and replace NAs while we're at it.\n    has_images_correct2 = ifelse(is.na(images) == FALSE, TRUE, FALSE))\n\ncombined4 %>%\n  filter(has_images_correct2 == TRUE) %>%\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18\n```\n:::\n\n```{.r .cell-code}\ncombined4 %>%\n  filter(has_images_correct2 == FALSE) %>%\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1863\n```\n:::\n:::\n\n\nSo this method of recoding works. My approach would be to first copy the entire processing code from line 140 and update the coding of images at 890 and re-run the whole thing and see what was produced. But more detailed checking of other steps might be required, depending on the application.\n",
    "supporting": [
      "UFOs_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}